apc_params:
  # Criterion to use when deciding final solution after itering
  # over multiple object variants and table heights.
  # 0 - Use PERCH solution cost (smaller the better)
  # 1 - Use number of scene points within the object volume (larger the better)
  solution_criterion: 1

  # Iterate over tabel_height + delta, for all delta in support_height_deltas
  # delta is in meters.
  support_height_deltas: [0, 0.01, 0.02]




